server:
   port: 8080
spring:
   profiles:
     active: ${SPRING_PROFILES_ACTIVE}
   security:
      oauth2:
         client:
            registration:
               google:
                  client-id: 290841963773-mba17llg18pv13endjkngra3oink92jv.apps.googleusercontent.com
                  client-secret: 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
               facebook:
                  client-id: 287841917045961
                  client-secret: b10925744cfb5cb3976fcdb63005c328
               github:
                  client-id: 17ae0530d87a1ccc9e49
                  client-secret: 7ff2dc2b1432936a764f69dd9ccc0dcf1a114ee6
   mvc:
      pathmatch:
         matching-strategy: ant_path_matcher
springdoc:
   api-docs:
      version: openapi_3_0
      enabled: true
   swagger-ui:
      enabled: true
      path: /swagger-ui


